//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemSinglApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parts
    {
        public int PartId { get; set; }
        public int RequestId { get; set; }
        public string PartName { get; set; }
        public int Quantity { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual Requests Requests { get; set; }
    }
}
