//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemSinglApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.Comments = new HashSet<Comments>();
            this.Parts = new HashSet<Parts>();
        }
    
        public int RequestId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string EquipmentType { get; set; }
        public string Model { get; set; }
        public string ProblemDescription { get; set; }
        public int UserId { get; set; }
        public int RequestStatusId { get; set; }
        public Nullable<int> TechnicianId { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parts> Parts { get; set; }
        public virtual Technicians Technicians { get; set; }
        public virtual RequestStatuses RequestStatuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
